# Generated by Django 4.1.2 on 2023-04-09 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameRole', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('IdTour', models.IntegerField(primary_key=True, serialize=False)),
                ('TourName', models.CharField(max_length=225)),
                ('TourDestination', models.CharField(max_length=225)),
                ('TourPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('UserEmail', models.CharField(max_length=255)),
                ('UserPassword', models.CharField(max_length=255)),
                ('UserDob', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TourUser',
            fields=[
                ('TourUser', models.IntegerField(primary_key=True, serialize=False)),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.tour')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.user')),
            ],
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.role')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reviews', models.CharField(max_length=225)),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.tour')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.user')),
            ],
        ),
    ]
