# Generated by Django 4.1.2 on 2023-04-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Avgrating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='Address',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='Desc',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='Distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='Featured',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='Photo',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
