# Generated by Django 4.1.2 on 2023-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0002_history_avgrating_tour_address_tour_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idUser',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
