# Generated by Django 4.1.2 on 2023-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_alter_user_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='IdTour',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
