# Generated by Django 4.1.2 on 2023-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0004_alter_tour_idtour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserDob',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserEmail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
