# Generated by Django 4.1.2 on 2023-04-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0005_alter_user_userdob_alter_user_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touruser',
            name='TourUser',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
