# Generated by Django 4.1.2 on 2023-04-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0006_alter_touruser_touruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='touruser',
            name='Date',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='touruser',
            name='Fullname',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='touruser',
            name='Guest',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='touruser',
            name='Phone',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrole', to='Entity.role'),
        ),
    ]
