# Generated by Django 4.1.2 on 2023-04-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0007_touruser_date_touruser_fullname_touruser_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touruser',
            name='TotalAmount',
            field=models.IntegerField(null=True),
        ),
    ]
