# Generated by Django 4.1.2 on 2023-05-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0008_touruser_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touruser',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
